{
  "uuid": "17e79349-4184-4198-a2b2-68ab853783bc",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_funcattrs.cpython-312.pyc",
  "size": 1164,
  "modified": "2025-05-28T17:29:55.207457025Z",
  "created": "2025-05-28T17:29:55.207457025Z",
  "sha256_hash": "1f33e5d400538ae8072d38c06c1c22b88c1529ecfc432d97434d7f0e21241edf",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.910422925Z"
}