{
  "uuid": "1f0a29e3-3fb9-453d-a37f-16fab0d49192",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_map.cpython-312.pyc",
  "size": 4507,
  "modified": "2025-05-28T17:29:55.210456986Z",
  "created": "2025-05-28T17:29:55.210456986Z",
  "sha256_hash": "a208d3d6c156b420970713d0306f99930040c6ec09b5ea008d437f47496e5581",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.182952452Z"
}