{
  "uuid": "28e5b323-c4bf-4909-8a4d-b8559e4e2c2f",
  "path": "/lib/python3.12/test/__pycache__/test_baseexception.cpython-312.pyc",
  "size": 11238,
  "modified": "2025-05-28T17:29:53.560478652Z",
  "created": "2025-05-28T17:29:53.560478652Z",
  "sha256_hash": "de15193ed7814e7c41b01179d3ef5bdfa0d7e93845280a48f7e6cfc5373f4531",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:08.156277462Z"
}