{
  "uuid": "2c9f74dd-3a2e-4bb6-8939-73eb2a934a8c",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_long.cpython-312.pyc",
  "size": 836,
  "modified": "2025-05-28T17:29:55.210456986Z",
  "created": "2025-05-28T17:29:55.210456986Z",
  "sha256_hash": "dc3806edb50d4c2719c9bd1f0cca2c17724b56cd11db383a78b79cb807a214c8",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.911205972Z"
}