{
  "uuid": "326fec3c-adeb-4c07-a350-86ad50fe5214",
  "path": "/lib/python3.12/asyncio/__pycache__/exceptions.cpython-312.pyc",
  "size": 3081,
  "modified": "2025-05-09T05:11:41.839899518Z",
  "created": "2025-05-09T05:11:41.839899518Z",
  "sha256_hash": "f6cafdc78c74c9c735996b2e03f41bce1578146861abe743a922cb295af637a3",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:08.651847858Z"
}