{
  "uuid": "380d369f-7692-4631-ac6e-5e4f28d17088",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_metaclass.cpython-312.pyc",
  "size": 10463,
  "modified": "2025-05-28T17:29:55.210456986Z",
  "created": "2025-05-28T17:29:55.210456986Z",
  "sha256_hash": "7df4240b1706b9ff5f6e747de3e27160e4ec1c3c4d8078f9b3ff39a08fd862af",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.186750637Z"
}