{
  "uuid": "3a84d93b-0fe5-4e0a-83bc-285d507c6ebf",
  "path": "/lib/python3/dist-packages/attr/__pycache__/exceptions.cpython-312.pyc",
  "size": 3548,
  "modified": "2025-02-15T08:11:54Z",
  "created": "2025-05-09T05:07:26.535796133Z",
  "sha256_hash": "606c49ca55cd384d9318c3fa39fb2f9b373a0bde5fcc20f6708a3edf19473a26",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:33.715779344Z"
}