{
  "uuid": "3ea0f7b3-5fbc-4ed1-9ce3-0be92107e751",
  "path": "/usr/lib/python3.12/email/__pycache__/errors.cpython-312.pyc",
  "size": 7021,
  "modified": "2025-05-09T05:11:41.190909425Z",
  "created": "2025-05-09T05:11:41.190909425Z",
  "sha256_hash": "71914d4846a49a539230a1b0222dc7c1c2b093dd95ad02fcf244774319f271da",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.989968124Z"
}