{
  "uuid": "47ee5ed2-b528-4562-a33f-0f75dc621bc1",
  "path": "/usr/lib/python3.12/test/__pycache__/test_exceptions.cpython-312.pyc",
  "size": 113637,
  "modified": "2025-05-28T17:29:54.026472533Z",
  "created": "2025-05-28T17:29:54.026472533Z",
  "sha256_hash": "2ff2fc23e78d2b473057f403144b63c74440cc03548b567907468654797f3a77",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:03.541210376Z"
}