{
  "uuid": "59804cab-8133-4a1a-b1e5-7990d3c1cf57",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_urllib.cpython-312.pyc",
  "size": 9201,
  "modified": "2025-05-28T17:29:55.215456920Z",
  "created": "2025-05-28T17:29:55.215456920Z",
  "sha256_hash": "30fd87a2aafb3bd7e1a9c90833eb67673b57a88063fb3ce5ae570d186f0f87e6",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.912302170Z"
}