{
  "uuid": "7190171d-3060-4563-9610-23201f895a02",
  "path": "/lib/python3.12/lib2to3/fixes/__pycache__/fix_intern.cpython-312.pyc",
  "size": 1404,
  "modified": "2025-05-28T17:29:55.209456999Z",
  "created": "2025-05-28T17:29:55.209456999Z",
  "sha256_hash": "968d294176c8ba0dee596890bd391aa51e469324dde2e123527b25b3c0a149f1",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:47:09.182018159Z"
}