{
  "uuid": "7ca032bd-a448-4bd7-963c-59c67e141433",
  "path": "/lib/python3/dist-packages/attr/exceptions.pyi",
  "size": 539,
  "modified": "2024-02-29T21:44:40Z",
  "created": "2025-05-09T05:07:26.532796179Z",
  "sha256_hash": "cd9abc6c2527280cbd983b41130e366613e1014207a1329e7434089c90fcf373",
  "file_type": {
    "Other": "pyi"
  },
  "permissions": 33188,
  "is_executable": false,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:33.717944714Z"
}