{
  "uuid": "a74ba7cc-f33a-4bd7-9be0-516229565063",
  "path": "/usr/lib/python3/dist-packages/cryptography/__pycache__/exceptions.cpython-312.pyc",
  "size": 2406,
  "modified": "2025-02-15T08:12:01Z",
  "created": "2025-05-09T05:07:26.736793066Z",
  "sha256_hash": "34d1f22c2badd08afa4191046e78d9d134e26a0bc5ea137bc3e0a3534794b7b7",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:45:26.012033011Z"
}