{
  "uuid": "ab3b8f68-966f-4e95-8b97-7644772885b4",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_import.cpython-312.pyc",
  "size": 4256,
  "modified": "2025-05-28T17:29:55.208457012Z",
  "created": "2025-05-28T17:29:55.208457012Z",
  "sha256_hash": "7f1f3050a21c0d85f6ee190348904024428a983b6db92b0195f72b39832eb29e",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.906826005Z"
}