{
  "uuid": "cab61f5b-99b9-4370-8bae-1b61dfc342ff",
  "path": "/usr/lib/python3/dist-packages/xdg/__pycache__/Exceptions.cpython-312.pyc",
  "size": 4635,
  "modified": "2025-02-15T08:11:58Z",
  "created": "2025-05-09T05:07:27.519781118Z",
  "sha256_hash": "1ad11113e4a1634109226457b936a4a3ec6ac8a00db0ec338232c833d67f7344",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:45:25.878984150Z"
}