{
  "uuid": "d249ef71-8220-4e84-91e2-1e5c4ad29b20",
  "path": "/usr/lib/python3/dist-packages/aptdaemon/errors.py",
  "size": 7460,
  "modified": "2023-05-22T20:24:55Z",
  "created": "2025-05-09T05:07:26.511796499Z",
  "sha256_hash": "7240202836f1dd308abcd08de6c43bf77c4825a5eaef9078a634c8c1d80d044d",
  "file_type": "Script",
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:45:26.565160329Z"
}