{
  "uuid": "e659292d-59cf-466d-8faf-fe2d6a190202",
  "path": "/usr/lib/python3.12/lib2to3/fixes/__pycache__/fix_has_key.cpython-312.pyc",
  "size": 4214,
  "modified": "2025-05-28T17:29:55.208457012Z",
  "created": "2025-05-28T17:29:55.208457012Z",
  "sha256_hash": "ef27e18ed9d4b94e1eaecae70dcbe901646a87165ba3993cd0d39833f242c53f",
  "file_type": {
    "Other": "pyc"
  },
  "permissions": 33188,
  "is_executable": true,
  "is_signed": false,
  "code_signature": null,
  "bundle_info": null,
  "scan_timestamp": "2025-06-01T18:46:04.908021910Z"
}